language: python
python:
  - "3.6"
install:
  - python setup.py install
  - pip install coveralls
  - pip install pycodestyle
script:
  - pycodestyle
  - python setup.py nosetests
after_success:
  - coveralls
